fixtures:
    repositories:
        stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
        nodejs: git://github.com/puppet-community/puppet-nodejs.git
        systemd: git://github.com/justin8/justin8-systemd.git
    symlinks:
        ghost: "#{source_dir}"
